//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Natiga
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stage_New_Search
    {
        public double seating_no { get; set; }
        public string arabic_name { get; set; }
        public Nullable<double> total_degree { get; set; }
        public Nullable<double> student_case { get; set; }
        public string student_case_desc { get; set; }
        public Nullable<double> c_flage { get; set; }
    }
}
